#!/usr/bin/with-contenv bash

# rename user
deluser syslog
usermod abc -l syslog
delgroup syslog
groupmod abc -n syslog

# permissions
chown -R syslog:syslog /config

if [ ! -d /log ]; then
  mkdir /log
fi
chown -R syslog:syslog /log
chmod -R 750 /log
